image: tetraweb/php

before_script:
- git submodule sync --recursive
- git submodule update --init --recursive
- printf "deb http://archive.debian.org/debian/ jessie main\ndeb-src http://archive.debian.org/debian/ jessie main\ndeb http://security.debian.org jessie/updates main\ndeb-src http://security.debian.org jessie/updates main" > /etc/apt/sources.list
- curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
- apt-get update
- apt-get install zip unzip lftp
- php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
- php composer-setup.php
- php -r "unlink('composer-setup.php');"
- php composer.phar install


deploy:
  only:
   refs:
    - master
  script:
  - composer install --optimize-autoloader --no-dev
  - zip -rq economy.zip . -x ".*" "*.md" public/\* deploy-scripts/\* laradock/\* tests/\* "*.js" "*.json" "*.lock" "*.sh" "phpunit.xml"
  - lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD skyclubitalia.it;  put -O ./domains/skyclubitalia.it/public_html/economy deploy-scripts/cleanDatabase.php"
  - curl skyclubitalia.it/economy/cleanDatabase.php
  - lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD skyclubitalia.it;  put -O ./domains/skyclubitalia.it/EconomyREST/ economy.zip"
  - lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD skyclubitalia.it;  put -O ./domains/skyclubitalia.it/public_html/economy deploy-scripts/unzip.php deploy-scripts/migrate.php"
  - curl skyclubitalia.it/economy/unzip.php
  - curl skyclubitalia.it/economy/migrate.php
  - lftp -e  "set ftp:ssl-allow no; rm /domains/skyclubitalia.it/public_html/economy/unzip.php /domains/skyclubitalia.it/public_html/economy/migrate.php /domains/skyclubitalia.it/public_html/economy/cleanDatabase.php; bye" -u $FTP_USERNAME,$FTP_PASSWORD skyclubitalia.it
  - lftp -e  "set ftp:ssl-allow no; rm /domains/skyclubitalia.it/EconomyREST/economy.zip; bye" -u $FTP_USERNAME,$FTP_PASSWORD skyclubitalia.it

