image: tetraweb/php

before_script:
- apt-get update
- apt-get install zip unzip lftp
- php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
- php composer-setup.php
- php -r "unlink('composer-setup.php');"
- php composer.phar install


deploy:
  only:
   refs:
    - master
  script:
  - composer update
  - zip -rq economy.zip . -x .idea/\* .gitignore .env public/\* .git/\* deploy-scripts/\*
  - lftp -c "set ftp:ssl-allow no; open -u skyclubi,avioweb skyclubitalia.it;  put -O ./domains/skyclubitalia.it/EconomyREST/ economy.zip"
  - lftp -c "set ftp:ssl-allow no; open -u skyclubi,avioweb skyclubitalia.it;  put -O ./domains/skyclubitalia.it/public_html/economy deploy-scripts/unzip.php deploy-scripts/migrate.php"
  - curl skyclubitalia.it/economy/unzip.php
  - curl skyclubitalia.it/economy/migrate.php
  - lftp -e  "set ftp:ssl-allow no; rm /domains/skyclubitalia.it/public_html/economy/unzip.php /domains/skyclubitalia.it/public_html/economy/migrate.php" -u skyclubi,avioweb skyclubitalia.it

