version: "3.8"
services:
  app:
    depends_on: 
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    image: economyrest-app
    container_name: economyrest-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    networks:
      - app-network

  db:
    image: mysql:5.6.49
    container_name: economyrest-db
    volumes:
      - db_data:/var/lib/mysql
      - ./development/db_init_script.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_USER: root,
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: economyrest-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: economyrest-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./development/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  db_data:
    driver: local
