version: "3.8"
services:
  db:
    image: mysql:8.0.23
    volumes:
      - db_data:/var/lib/mysql
      - ./test_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_USER: root,
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  db_data:
    driver: local
